### ISSUE TITLE
Upgrade to 1.2 requires restart

### ISSUE THREAD

**Issue by solugebefola** [timescale/docs.timescale.com-content#102]
Need to denote which version upgrades require restart and which don't

**Comment by davidkohn88** [comment]
Is there a specific section of the docs this should go in?

**Comment by solugebefola** [comment]
`update-db.md`

**Comment by solugebefola** [comment]
bump

**Comment by solugebefola** [comment]
@svenklemm can you take a look?  Newly related to https://timescaledb.slack.com/archives/C4GT3N90X/p1565612255452100

**Comment by solugebefola** [comment]
@svenklemm I don't know if this has been addressed in any recent PRs?  If not can you check it out?

**Comment by mfreed** [comment]
@solugebefola Are you thinking this goes in the upgrade section?  I.e., any release-specific instructions?

**Comment by solugebefola** [comment]
@mfreed I'm not sure.  I made this issue in response to a slack thread, but I don't know if it still exists.  I don't have release-specific details...

**Comment by NunoFilipeSantos** [comment]
@solugebefola I'm closing this. Feel free to reopen if it becomes relevant again.
