### ISSUE TITLE
Wrong option name in CREATE VIEW api documentation

### ISSUE THREAD

**Issue by NomAnor** [timescale/docs.timescale.com-content#147]
The option `timescaledb.create_group_index` does not exist, looking in the source it is called `timescaledb.create_group_indexes`.

**Comment by gayyappan** [comment]
Yes, the correct option is : timescaledb.create_group_indexes

**Comment by mfreed** [comment]
Fixed in https://github.com/timescale/docs.timescale.com-content/pull/149
