### ISSUE TITLE
Add in information on how to add dimensions / update chunk_time_interval with cont aggs

### ISSUE THREAD

**Issue by dianasaur323** [timescale/docs.timescale.com-content#199]
SELECT _timescaledb_internal.stop_background_workers();
SELECT _timescaledb_internal.start_background_workers();

**Comment by dianasaur323** [comment]
hey @gayyappan tracking this so that we don't forget - related to the user who wanted to update their underlying hypertable, but things kept failing. Should we document this, or do you think we should add an issue to implement something like a public API for this use case?

**Comment by solugebefola** [comment]
@gayyappan I don't know if this has been addressed already.  If so, can you close?

**Comment by solugebefola** [comment]
Bumping again.  Has this been documented?

**Comment by gayyappan** [comment]
Docs have this information now. 

> Best Practices
> Modifying the Materialization Hypertable: Advanced users may find the need to modify certain properties of the materialization hypertable (e.g. chunk size) or to create further indexes. To help with such, we can find the name of the materialization hypertable in the timescaledb_information.continuous_aggregates view (API Docs). We can then modify the materialization hypertable as if it were a normal hypertable. For instance, we may want to set the materialization hypertable's chunk_time_interval to something other than the default; this can be accomplished by running set_chunk_time_interval on the materialization hypertable.
