### ISSUE TITLE
Cannot navigate the documentation website via keyboard on Firefox 69

### ISSUE THREAD

**Issue by gitter-me** [timescale/docs.timescale.com-content#218]
On Firefox I cannot navigate via keyboard (arrow keys, page up/down, spacebar).
I'm not sure if it is related to my machine, but all other pages are working correctly.

So unfortunately no steps to reproduce.
But perhaps someone else can share their experience on firefox.

**Comment by solugebefola** [comment]
Should be fixed.  Please check and close if solved?  Thx.
