### ISSUE TITLE
Update supported version note on installation pages

### ISSUE THREAD

**Issue by k-rus** [timescale/docs.timescale.com-content#273]
Currently each installation page contains:
> Note: TimescaleDB requires PostgreSQL 9.6.3+, 10.9+, or 11.4+

However, Support for 9.6 and 10 are deprecated.

A proposal:
> Note: TimescaledDB requires PostgreSQL 11.4+.

Should we mention that support for PostgreSQL 9.6.3+, 10.9+ is deprecated and support for PostgreSQL 12 is coming?

**Comment by k-rus** [comment]
A page to change https://github.com/timescale/docs.timescale.com-content/blob/master/getting-started/installation-homebrew.md and many other pages.

**Comment by bboule** [comment]
I think this is a good idea I think we should also consider a matrix document on GitHub that outlines our current support posture for PG versions (Supported, Deprecated, EOL, Coming Soon)?  Thoughts?

**Comment by k-rus** [comment]
I believe @mkindahl already implemented it. Can you confirm and close the issue if so?
