### ISSUE TITLE
Create hypertable clarification

### ISSUE THREAD

**Issue by ARao0123** [timescale/docs.timescale.com-content#308]
In the documentation I see the following for create_hypertable:

```
Convert table conditions to hypertable with time partitioning on time and space partitioning (4 partitions) on location:

SELECT create_hypertable('conditions', 'time', 'location', 4);
```

This is not an issue, just that reading that description I do not follow what is happening.
What does 4 partitions on location mean?
Some sample output would help.

**Comment by bboule** [comment]
Move this issue over to our docs repo for triage!!
