### ISSUE TITLE
Gapfill examples should infer range from WHERE

### ISSUE THREAD

**Issue by mfreed** [timescale/docs.timescale.com-content#309]
This uses an older syntax, which needs the START/STOP in the function declaration.  We should use the "easier/prettier" example of where this is inferred from a WHERE predicate:

https://docs.timescale.com/latest/using-timescaledb/reading-data#gap-filling

**Comment by solugebefola** [comment]
Can

**Comment by solugebefola** [comment]
Assuming closed with the PR merge
