### ISSUE TITLE
Hyperlink not working

### ISSUE THREAD

**Issue by threadcat** [timescale/docs.timescale.com-content#342]
Instruction page:
https://github.com/timescale/docs.timescale.com-content/blob/master/getting-started/installation-yum.md

contains hyperlink for '...instructions for adding a postgres user' which is not working:
suite.opengeo.org/docs/latest/dataadmin/pgGettingStarted/firstconnect.html

**Comment by mfreed** [comment]
Addressed in https://github.com/timescale/docs.timescale.com-content/pull/378/

**Comment by mfreed** [comment]
Still broken in Ubuntu AMI:  https://docs.timescale.com/latest/getting-started/installation/ami/installation-ubuntu-ami
