### ISSUE TITLE
Missing link for PG12 in installation page?

### ISSUE THREAD

**Issue by yyjdelete** [timescale/docs.timescale.com-content#373]
Page: https://docs.timescale.com/latest/getting-started/installation/windows/installation-windows

Seems the default version is updated to 1.7, and https://timescalereleases.blob.core.windows.net/windows/timescaledb-postgresql-12_1.7.0-windows-amd64.zip is already available. But there is no option to choose `PostgreSQL version:12`.

Is it just forget to add the new version, or support for pg12 in 1.7.0 is still in beta stage?

**Comment by blagojts** [comment]
Our documentation is having some last minute changes done. Version 1.7 was released, it's not a beta, and we'll publish the new docs soon

**Comment by mfreed** [comment]
https://github.com/timescale/docs.timescale.com-content/pull/374
