### ISSUE TITLE
[Change] Windows: Add tip to install as admin if PG installed as admin

### ISSUE THREAD

**Issue by mfreed** [timescale/docs.timescale.com-content#414]
Users somewhat report permissions errors on Windows installations:

> I have PostgreSQL 12 installed already. When I run setup.exe, I get the error "ERROR: could not copy file 'timescaledb-1.7.1.dll': open C:/PROGRA~1/POSTGR~1/12/lib/timescaledb-1.7.1.dll: Access is denied." Can I get some help completing my installation?

Problem is often related to admin privileges, in which case they should also do install/setup using admin privileges.

Suggested change:  Add *TIP* to WIndows install:   https://docs.timescale.com/latest/getting-started/installation/windows/installation-windows

**Comment by solugebefola** [comment]
Checking on this:  Is it still relevant? @k-rus, @ryanbooz I recall you making modifications to the windows install page.  Did either of you incorporate any changes that address this issue?
