### ISSUE TITLE
[Change] Clarify that installing old versions require one to name version explicitly

### ISSUE THREAD

**Issue by mfreed** [timescale/docs.timescale.com-content#415]
Clarify to users that when installing a non-latest extension, you need to explicitly specify the version being installed:

```CREATE EXTENSION timescaledb VERSION '1.7.0';```

(The way our packaging works, a common "loader" package is a dependency that is always based on the latest, but has support for prior versions.)

**Location(s)**
https://docs.timescale.com/latest/getting-started/setup
https://docs.timescale.com/latest/getting-started/installation/docker/installation-docker#postgis-docker

etc.

**Comment by sarahandromeda** [comment]
Hello!

So this TIP that was added to the docs in this Pull Request seems to no longer be in the documentation! Would you all be able to add it back in? I spent quite a long time trying to figure this out and finally locating this old Issue it was finally confirmed it! Thank y'all!

Ps. Commented on the wrong object. Moved my comment here instead!
