### ISSUE TITLE
Make clear in docs what multinode options are critical

### ISSUE THREAD

**Issue by erimatnor** [timescale/docs.timescale.com-content#417]
Everyone running multinode needs at least these standard PostgreSQL options set:

* `enable_partitionwise_aggregate=true`
* `max_prepared_transactions=100`

It must be really clear in the docs that these options are critical since they aren't set by default.

**Comment by mfreed** [comment]
- `max_prepared_transactions` is specified in https://docs.timescale.com/v2.0/getting-started/setup-multi-node-basic/setup-multi-node-auth

- `enable_partitionwise_aggregate` appears to be here, although more as tip:  https://docs.timescale.com/v2.0/using-timescaledb/distributed-hypertables#select

Is that okay, or do we need them elsewhere, @erimatnor ?

**Comment by solugebefola** [comment]
Is this resolved by #587 ?

**Comment by solugebefola** [comment]
@erimatnor can this issue be closed?
