### ISSUE TITLE
[Update] Clarify pg_dumpall with TimescaleDB dump/restore

### ISSUE THREAD

**Issue by mfreed** [timescale/docs.timescale.com-content#433]
There are some details when using pg_dumpall.  We should clarify this in the docs.

https://docs.timescale.com/latest/using-timescaledb/backup

**Comment by solugebefola** [comment]
Who would be the best person to handle?

**Comment by td-harness** [comment]
I am in a tough spot here, could anyone clarify on the details here around restoration of a backup generated using pg_dumpall --Quite a large amount of data and it seems to only partially restore the data(3 out of like 20 tables) - I am throwing the kitchen sink at it here(psql < sqlfile.out fails, wrong format for pg_restore it seems, and cannot convert that I am aware of without full restoration) - it is around 25GB of data IIRC, I really hope I did not make a big booboo.

**Comment by Loquacity** [comment]
Hi @td-harness I'm sorry to hear you're having trouble! This is a very old thread in a disused repository. I recommend you try joining our Slack community, or the forum for help instead: https://www.timescale.com/community

**Comment by anthonyorona** [comment]
From what I am able to gather from a google search, pg_dumpall for logical backups is not supported by TimeScaleDB. The official docs (linked from 2020) were never updated.

![Screenshot from 2022-09-28 13-52-10](https://user-images.githubusercontent.com/70772352/192886409-d0489ea6-5cab-43e3-bf6c-c1dc69f01521.png)

**Comment by td-harness** [comment]
This is the conclusion I have come to, makes sense at least, thanks for looking into it greatly appreciated.

 

Jeremy
