### ISSUE TITLE
[Bug/Typo] CentOS 8 installation instructions make it impossible to install postgresql12-server

### ISSUE THREAD

**Issue by dbech** [timescale/docs.timescale.com-content#440]
**Describe the bug**
Documentation found at https://docs.timescale.com/latest/getting-started/installation/rhel-centos/installation-yum doesn't account for module filtering when using Centos 8 and PostgreSQL 12
**Location**

https://docs.timescale.com/latest/getting-started/installation/rhel-centos/installation-yum

More info can be found here: https://github.com/timescale/timescaledb/issues/1882

**Comment by solugebefola** [comment]
@dbech just following up, this should be resolved now, so closing this issue.  Can you confirm?  If not resolved, you can reopen.
