### ISSUE TITLE
[Bug] Issues with caggs ALTER VIEW

### ISSUE THREAD

**Issue by k-rus** [timescale/docs.timescale.com-content#453]
The first page of [ALTER VIEW](https://docs.timescale.com/latest/api#continuous_aggregate-create_view-with) API description contains link to options, but it doesn't lead anywhere, at least clicking it in Safari doesn't do anything:
>ALTER VIEW statement can be used to modify the WITH clause options for the continuous aggregate view.

The BNF is confusing and is not fully correct. It is:
```sql
ALTER VIEW <view_name> SET ( timescaledb.option =  <value> )
```
I think it is good to demonstrate that `option` should be replaced with valid value and several options can be specified in the command. For example:
```sql
ALTER VIEW <view_name> SET ( timescaledb.<option> =  <value> [, ... ] )
```
And then describe `<option>` and `<value>` in the parameters in generic way with link to possible options. Note that only `<view_name>` is currently described.

**Comment by mfreed** [comment]
@k-rus Is this still an issue in 2.0?  If so, can you propose a concrete suggested fix?

**Comment by k-rus** [comment]
> @k-rus Is this still an issue in 2.0? If so, can you propose a concrete suggested fix?

I will look at it.
