### ISSUE TITLE
[Update] Clarify that indexes are not used for compressed chunks

### ISSUE THREAD

**Issue by cocowalla** [timescale/docs.timescale.com-content#470]
It would be really useful to update the docs to mention that indexes are not used when reading from compressed chunks - this is important info, but not mentioned anywhere.

**Location(s)**
https://docs.timescale.com/latest/using-timescaledb/compression

**Comment by solugebefola** [comment]
Yup, we're adding that to our next version of docs.  Thanks for the heads up!
