### ISSUE TITLE
[Bug/Typo] Broken hyperlink in "Ingesting Data"

### ISSUE THREAD

**Issue by johndburk** [timescale/docs.timescale.com-content#471]
**Add the appropriate label(s) -->**

**Describe the bug**
`Writing Data` link in the first paragraph of Ingesting Data broken, no URL behind it

**Location**
https://docs.timescale.com/latest/using-timescaledb/ingesting-data
**Screenshots**

![image](https://user-images.githubusercontent.com/29608541/90964435-667d0f80-e475-11ea-8140-51c230e473df.png)

**Device and browser**
Desktop (centos-7.6)
Chrome Version 83.0.4103.97 (Official Build) (64-bit)

**Comment by johndburk** [comment]
Ignore: turns out the link does work if you click directly on it, but not if you try to middle-click to "open in new tab", and rollover shows no underlying link.  Seems to be the approach taken in a lot of places in the docs.

Not really a fan; being able to open a referred page in a new tab while keeping the referring page open is really helpful when first encountering a doc set for a new product, as the reader will often jump back and forth between pages.

**Comment by solugebefola** [comment]
Yah, that's an implementation detail for our setup.  We're in the process of changing our underlying framework for docs so that page links will act as normal links with behavior that you would expect, like "open in new tab".  Thanks for the issue!
