### ISSUE TITLE
[Update] Informational Views

### ISSUE THREAD

**Issue by mfreed** [timescale/docs.timescale.com-content#484]
Informational views have been updated for 2.0

**Currently all @gayyappan**

**Remove:**

- [x] timescaledb_information.continuous_aggregate_stats  
- [x] timescaledb_information.compressed_chunk_stats
- [x] timescaledb_information.compressed_hypertable_stats
- [x] timescaledb_information.reorder_policies
- [x] timescaledb_information.drop_chunks_policies
- [x] hypertable_relation_size_pretty
- [x] chunk_relation_size_pretty
- [x] indexes_relation_size_pretty

**Update:**

- [x] timescaledb_information.hypertables (from timescaledb_information.hypertable)
- [x] timescaledb_information.continuous_aggregates 
- [x] timescaledb_information.jobs_stats
- [x] hypertable_detailed_size (from hypertable_relation_size)
- [x] chunk_detailed_size (from chunk_relation_size)

**Add:**

- [x] timescaledb_information.chunks
- [x] timescaledb_information.dimensions
- [x] hypertable_size
- [x] hypertable_index_size
- [x] Demonstrate how to use `pg_pretty` on size functions, since pretty API was removed
- [x] jobs

**Compression**
- [x] timescaledb_information.compression_settings
- [x] hypertable_compression_stats
- [x] chunk_compression_stats

**Comment by mfreed** [comment]
@gayyappan Is the `jobs` view done?

**Comment by gayyappan** [comment]
@mfreed Yes, all done. Just one more PR  to wrap this up ( parameter name changes for size utility functions).

**Comment by mfreed** [comment]
Should this issue be closed, then?  @gayyappan ?
