### ISSUE TITLE
[New] Custom job scheduling

### ISSUE THREAD

**Issue by mfreed** [timescale/docs.timescale.com-content#485]
**Using Custom Jobs**

- [x] New “using custom job scheduling” section describing how to use new jobs, how to schedule, etc. using new API functions ( https://docs.timescale.com/latest/using-timescaledb/custom-jobs )
- [x] Examples of both timestamp/interval and integer-based scheduling
- [x] 1-3 examples of custom jobs you could implement using framework

**API docs**

- [x] add_job
- [x] alter_job
- [x] run_job
- [x] delete_job

**Existing policy docs**

Note these are largely covered by different tasks, but keeping for completeness

- data retention policies (see also https://github.com/timescale/docs.timescale.com-content/issues/488)
- data reordering policies (added to https://github.com/timescale/docs.timescale.com-content/issues/488)
- compression policies (see also https://github.com/timescale/docs.timescale.com-content/issues/487)
- continuous aggregate policies (see also https://github.com/timescale/docs.timescale.com-content/issues/486)

**Comment by svenklemm** [comment]
integer vs time-based doesnt matter for the scheduling itself, it's up to the custom jobs to handle this
