### ISSUE TITLE
[Update] Continuous Aggregates

### ISSUE THREAD

**Issue by mfreed** [timescale/docs.timescale.com-content#486]
**Using Docs - Continous Aggregates**

- [x] Update documents for new framework (@mkindahl)
- [X] Instructions for migrating existing caggs from 1.x (In migration / changes from 1.x doc)
- [x] Clarify how to use with integer-partitioned hypertables (@mkindahl )
- [x] Update / expand limitations:  caggs on caggs, windowing functions, JOINs, etc.
- [x] Give recommendations for values when adding a policy.
- [x] Add use case for keeping aggregates while dropping raw data
- [x] Add use case for keeping aggregate 100% up-to-date with raw data
-  ~Add use case that optimizes for recent data refresh (e.g., policy to refresh recent data while manually refreshing historical data): https://github.com/timescale/timescaledb/issues/1634~

**Tutorial - Continuous Aggregates**

- [ ] Hide or update tutorial (https://docs.timescale.com/latest/tutorials/continuous-aggs-tutorial)

**API Docs - Continuous Aggregates**

- [x] Update API docs - https://docs.timescale.com/latest/api#continuous-aggregates
- [x] Update `CREATE MATERIALIZED VIEW` - https://docs.timescale.com/latest/api#continuous_aggregate-create_view (@mkindahl)
- [x] Update `ALTER VIEW` - https://docs.timescale.com/latest/api#continuous_aggregate-alter_view (@mkindahl )
- [x] Remove `REFRESH MATERIALIZED VIEW` - https://docs.timescale.com/latest/api#continuous_aggregate-refresh_view (note that this command is still pending removal)
- [x] Update `DROP VIEW` (e.g., CASCADE no longer needed) - https://docs.timescale.com/latest/api#continuous_aggregate-drop_view (@mkindahl)
- [x] Add `refresh_continuous_aggregate` (@mkindahl)
- [x] Add `add_continuous_aggregate_policy` (@mkindahl)
- [x] Add `remove_continuous_aggregate_policy` (@mkindahl)
- [x] Clarify `interger_now_func` (@mkindahl)

**Comment by mkindahl** [comment]
Linking issues does not work as I expected.

**Comment by mkindahl** [comment]
@mfreed What kind of clarifications did you have in mind for `set_integer_now` function? There is a quite elaborate example about that already. What do you think is missing?

**Comment by mfreed** [comment]
> @mfreed What kind of clarifications did you have in mind for `set_integer_now` function? There is a quite elaborate example about that already. What do you think is missing?

I think we are good now...

**Comment by mfreed** [comment]
I'm going to mark the "migrated" doc given the migrations work, and don't think at this point we need to have that more advanced use case of recent + advanced.  Can be inferred from docs.

**Comment by mfreed** [comment]
Moved tutorial update to new issue:  https://github.com/timescale/docs.timescale.com-content/issues/572

**Comment by mfreed** [comment]
Otherwise looks finished with tutorial as separate issue.
