### ISSUE TITLE
[Update] Remove enterprise license information

### ISSUE THREAD

**Issue by mfreed** [timescale/docs.timescale.com-content#491]
- [x] API Docs - Remove/hide `timescaledb_information.license` - https://docs.timescale.com/latest/api#timescaledb_information-license

- [x] API Docs - Remove/hide `timescaledb.license_key` - https://docs.timescale.com/latest/api#timescaledb_license-key

- [x] Telemetry - Remove description of enterprise license - https://docs.timescale.com/latest/using-timescaledb/telemetry

- [ ] Installation instructions also may include Enterprise info, e.g., see tip here: https://docs.timescale.com/latest/getting-started/installation/debian/installation-apt-debian

**Comment by k-rus** [comment]
> * [ ]  API Docs - Remove/hide `timescaledb_information.license` - https://docs.timescale.com/latest/api#timescaledb_information-license

@mfreed I suggest to keep information about the license, since users are confused if they have Apache or TSL installed.
