### ISSUE TITLE
[Change] Remove "Enterprise" tag from features in our API docs?

### ISSUE THREAD

**Issue by alexthinath** [timescale/docs.timescale.com-content#524]
**Describe the change**

Unsure if move_chunks is the only affected feature, but we've gotten two customer questions on this so far. This one is a little tricky since its also only available on community - we cant do it today on Forge or Cloud

<img width="1132" alt="Screen Shot 2020-10-06 at 12 21 35 PM" src="https://user-images.githubusercontent.com/57811449/95229451-96d30000-07ce-11eb-8eca-b9b0bc1f77c1.png">

**Location(s)**
https://docs.timescale.com/latest/api#move_chunk

**How soon is this needed?**
Unclear

**Comment by mfreed** [comment]
(For record, this change is in an upcoming docs PR.)
