### ISSUE TITLE
API Reference, time_bucket warning formatting error

### ISSUE THREAD

**Issue by shasderias** [timescale/docs.timescale.com-content#55]
See picture, probably an issue with the parser used? Reproduces in Chrome and Edge.

![2018-11-18 14_08_54-microsoft edge](https://user-images.githubusercontent.com/614153/48668916-b362e200-eb3b-11e8-90b7-1d2b7d3b3f62.png)

**Comment by solugebefola** [comment]
#54

**Comment by solugebefola** [comment]
Thanks for noticing.  We're already on it :) #54

**Comment by shasderias** [comment]
Ooh, saw the PR but did not notice the newlines. My bad. Sorry for the noise!
