### ISSUE TITLE
[Bug/Typo] LOCF shouldn't bound via WHERE clause when doing a select "look behind"

### ISSUE THREAD

**Issue by mfreed** [timescale/docs.timescale.com-content#602]
If you need to look below the starting value with an locf/gapfill, I don't think you can limit it via a WHERE clause on the bottom, as otherwise I believe the query planner won't "look behind" your bottom value (at least across chunks, if nothing else)?

If so, I think this example should drop the WHERE clause:

https://docs.timescale.com/latest/api#locf

![image](https://user-images.githubusercontent.com/205086/101025253-50d2b800-3543-11eb-817f-1cbd4c82faeb.png)

@svenklemm thoughts?

**Comment by svenklemm** [comment]
The outer WHERE-clause doesnt apply to the subquery and WHERE clause evaluation happens before aggregation/gapfill so the example is fine. The lookup-query is independant of the normal query and will look back as far as needed even if the outer query only picks up recent data
