### ISSUE TITLE
Installation on Mac does not provide instructions on how to get psql 

### ISSUE THREAD

**Issue by NunoFilipeSantos** [timescale/docs.timescale.com-content#674]
The section is about how to  installing psql on Mac but the current instructions do not provide that.
https://docs.timescale.com/latest/getting-started/install-psql-tutorial

**Comment by NunoFilipeSantos** [comment]
If you have `zsh: command not found: psql` this means you need to install psql before proceeding.

We recommend installing it over Homebrew:
`brew install postgresql`

**Comment by jonatas** [comment]
It's already [fixed](https://docs.timescale.com/latest/getting-started/install-psql-tutorial) with the new link of libpq tools explanation.
