### ISSUE TITLE
[Update] Document how to use distributed restore point on multinode

### ISSUE THREAD

**Issue by k-rus** [timescale/docs.timescale.com-content#685]
`create_distributed_restore_point` creates consistent restore points on nodes of a multinode. https://github.com/timescale/timescaledb/pull/3024 tests using the function and restoring a multinode with help `pg_basebackup`.

It is necessary to document how users can make backup and restore multinode with help of  `create_distributed_restore_point` and, e.g., `pg_basebackup`.
The target is 2.2 release where the function is expected to be included.

**Comment by erimatnor** [comment]
Note that it is not clear if, and how, users will be able to use this to do backup and restore on Forge initially. We might want to make an explicit note of this. FWIW, I believe users on Forge cannot use `pg_create_restore_point()` either.

**Comment by pmwkaa** [comment]
https://github.com/timescale/docs.timescale.com-content/pull/700

**Comment by pmwkaa** [comment]
PR merged.
