### ISSUE TITLE
[Bug/Typo]  No "Future Work" section in continuous aggs

### ISSUE THREAD

**Issue by mfreed** [timescale/docs.timescale.com-content#696]
I don't believe there is currently any "Future Work" section on Continuous Aggregations, but the option still exists in the nav bar:

https://docs.timescale.com/latest/using-timescaledb/continuous-aggregates#future-work

![image](https://user-images.githubusercontent.com/205086/113154040-9f4c4680-9205-11eb-99e6-177d2752c0d5.png)

**Comment by ramonguiu** [comment]
Already fixed.
