### ISSUE TITLE
[Bug/Typo] add an 's' under drop_chunks parameter written as 'cascade_to_materialization'

### ISSUE THREAD

**Issue by hardikm10** [timescale/docs.timescale.com-content#697]
**Describe the bug**
Parameter 'cascade_to_materializations' of drop_chunks is written without an 's' at the end which makes following this example easier to mess. See Screenshot.

**Location**
https://docs.timescale.com/v1.7/using-timescaledb/data-retention

**Screenshots**
<img width="492" alt="data-retention-typo" src="https://user-images.githubusercontent.com/8678005/113266424-e3694500-92f2-11eb-8ba6-52c5b3bbc2e5.png">

**Comment by jonatas** [comment]
Thanks for reporting @hardikm10! 

It's [already fixed](https://github.com/timescale/docs.timescale.com-content/blob/master/tutorials/tutorial-use-timescale-prometheus-grafana.md#data-retention-policies).
